#!/usr/bin/env python3
"""
SMD Password Entropy Audit Tool
=================================

This script verifies that all passwords generated by the SMI password
manager have at least 122 bits of Shannon entropy, as required by our
security claims.

SECURITY CLAIM:
    All deterministically generated passwords in our password manager
    contain at least 122 bits of Shannon entropy.

AUDIT PROCEDURE:
    1. Run this script to verify the entropy claim
    2. Review the output report
    3. Confirm all passwords tested have >= 122 bits of entropy
    4. Confirm the minimum entropy across all tests is >= 122 bits

METHODOLOGY:
    - Uses HKDF (RFC 5869) with SHA-256 for key derivation
    - Encodes output in Base95 (ASCII printable characters 32-126)
    - Computes Shannon entropy: H = -Σ p(x) * log2(p(x)) * length
    - Uses Welford's online algorithm for streaming statistics (O(1) memory)
    - Tests multiple iterations to account for random variation

DEPENDENCIES:
    - Python 3.6+
    - hkdf (pip install hkdf)

$Intent: Provide auditable proof that SMI passwords meet 122-bit entropy requirement $

================================================================================
AUDITOR GUIDE - Assumptions and Verification Requirements
================================================================================

ASSUMPTIONS MADE IN THIS AUDIT:

1. CRYPTOGRAPHIC PRIMITIVES:
   - HKDF (RFC 5869) with SHA-256 is cryptographically secure
   - The hkdf Python library correctly implements the HKDF specification
   - SHA-256 provides sufficient entropy extraction

2. KEY MATERIAL:
   - The IKM can be loaded from a .env file (AXIOM_IKM variable) or
     environment variable, with a hardcoded fallback for testing
   - The SALT value is hardcoded in this script
   - The IKM and SALT values used are the EXACT values used in production
     (provided by Key Broker Server when "Audit Mode" is turned on)
   - These values have sufficient initial entropy (IKM is a 128-bit UUID)
   - The IKM is kept secret and protected appropriately

3. PASSWORD GENERATION ALGORITHM:
   - Passwords are generated by: HKDF-Expand(SHA-256, PRK, info, length) -> Base95
   - The info parameter includes a counter to generate unique passwords
   - Base95 encoding uses ASCII characters 32-126 (95 printable characters)
   - The key length (len_bytes) is calculated to ensure minimum entropy

4. ENTROPY CALCULATION:
   - Shannon entropy is computed on the password STRING (not raw bytes)
   - Each Base95 character contributes up to log2(95) ≈ 6.57 bits of entropy
   - Total password entropy = sum of character entropies
   - The calculation includes ALL characters in the password

5. STATISTICAL METHODOLOGY:
   - Testing 1,000,000 samples provides >99.9999% confidence
   - 6-sigma confidence bound covers 99.999999% of the distribution
   - Welford's algorithm provides numerically stable online statistics

--------------------------------------------------------------------------------
WHAT THE AUDITOR MUST VERIFY:

1. SCRIPT INTEGRITY:
   ✓ Verify this is the exact script used in production
   ✓ Confirm the file has not been modified (check checksum/hash)
   ✓ Verify all dependencies (hkdf, hashlib) are standard/trusted

2. KEY MATERIAL:
   ✓ Confirm IKM is loaded from .env file (AXIOM_IKM) or environment
   ✓ Verify PRK proof values matches production system
   ✓ Confirm SALT value matches production system
   ✓ Verify IKM is stored securely and not hardcoded in other locations
   ✓ Check that IKM has sufficient entropy (128-bit UUID is adequate)

3. PASSWORD GENERATION:
   ✓ Verify the password generation algorithm matches production code
   ✓ Confirm Base95 encoding uses the correct alphabet (32-126)
   ✓ Check that the key length calculation is appropriate

4. ENTROPY CLAIM:
   ✓ Review that ALL tested passwords have >= 122 bits
   ✓ Verify minimum entropy in report is >= 122 bits
   ✓ Check that the confidence bound supports the claim

5. REPRODUCIBILITY:
   ✓ Run the audit multiple times to confirm consistent results
   ✓ Test on independent hardware if possible
   ✓ Verify results are reproducible given the same inputs

6. OUTPUT REVIEW:
   ✓ Examine the JSON report file for completeness
   ✓ Verify all statistics are reasonable
   ✓ Check for any failures or warnings in the output

LIMITATIONS AND NOTES:

- This audit tests the ENTROPY of passwords, not their randomness
- Shannon entropy is an upper bound on the true entropy
- The actual entropy may be lower if the HKDF output has biases
- However, with proper HKDF and sufficient key material, biases are negligible
- The 122-bit claim is about the password STRING after Base95 encoding
- The raw OKM key has higher entropy (216 bits for 27 bytes)
- Base95 encoding may slightly reduce entropy due to padding

INTERPRETING RESULTS:

- PASSED: All tests met the 122-bit minimum. Claim is verified.
- FAILED: One or more passwords had < 122 bits. Claim is NOT verified.
- INCOMPLETE: Audit was interrupted. Results may not be conclusive.

The confidence statement (e.g., "With 6-sigma confidence, the true minimum is
>= X bits") indicates the statistical certainty that the worst-case password
meets the entropy requirement.

================================================================================
"""

from crypto import *
from test.entropy import *
from test.report import *

def main():
    banner()
    ikm = load_ikm()
    prk = derive_prk(ikm)
    stats = Welford()
    for i in range(MAX_ITERATIONS):
        stats.update(shannon_entropy(generate_password(prk,i)))
    summary(stats)

if __name__=='__main__':
    main()

# "The entry point orchestrates the proof, bringing structure to random chaos." -- Jack S. Molett, BlockSmith Orchestrator [Proof Orchestration, 2026]
